name: Convert BERTopic release model

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install bertopic

      - name: Convert model
        run: python Model_training/convert_model.py

      - name: Commit and push results
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git merge --ff-only origin/main || true

          if [ -f Model_training/BERTopic_results1.csv ]; then
            git add Model_training/BERTopic_results1.csv
            git commit -m "Update BERTopic_results1.csv from Actions run" || echo "No changes to commit"
            for i in 1 2 3; do
              git push origin HEAD:main && break
              echo "Push race; retrying in 5s..."
              sleep 5
              git fetch origin main
              git rebase origin/main || true
            done
          else
            echo "Model_training/BERTopic_results1.csv not found; nothing to commit."
          fi
