name: RSS Extraction

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:  
  
permissions:
  contents: write
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Pull latest articles
        run: git pull origin main --rebase

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install spaCy English model
        run: python -m spacy download en_core_web_sm

      - name: Run script
        env: 
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY_NEWS }}
          GEMINI_API_KEY_X: ${{ secrets.GEMINI_API_KEY_X }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          COOKIE_HEADER: ${{ secrets.COOKIE_HEADER }}
        run: |
          python Online_Extraction/RSS_extraction.py

      - name: commit and push extracted JSON files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase origin main
          git add Online_Extraction/*.json all_RSS.json  # Explicitly add all you want tracked
          git commit -m "Auto-update extracted JSON files" || echo "Nothing to commit"
          git push
