name: Run model_train.py Now
on:
  workflow_dispatch:

jobs:
  run_matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python_version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run model.py
        env: 
          RISKS_LIST: ${{ secrets.RISKS_LIST }}
        run: |
          python Model_training/model_validation.py

      - name: Commit and push JSON output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add risk_predictions.csv
          git commit -m "Auto-update extracted JSON files [skip ci]" || echo "No changes to commit"
          git push
        env:
          GIHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
