name: Run model.py Now
on:
  workflow_dispatch:

jobs:
  run_matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python_version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run model.py
        run: |
          python model.py

      - name: Commit and push model
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add my_model* # or path/to/my_model_directory
          git diff --cached --quiet || git commit -m "Update model"
          git push
