name: Run matrix.py Now
on:
  workflow_dispatch:

jobs:
  run_matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python_version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run matrix.py
        env:
          RISKS_LIST: ${{ secrets.RISKS_LIST }}
        run: |
          python matrix.py

      - name: Commit and push JSON output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add articles_with_risks.json
          git commit -m "Update JSON output"
          git push
