name: Midnight Run

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:  
  
permissions:
  contents: write
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env: 
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY_NEWS }}
          GEMINI_API_KEY_X: ${{ secrets.GEMINI_API_KEY_X }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
        run: |
          python run.py

      - name: commit and push extracted JSON files
        run: |
          git config --global user.name 'github-actions'
          git config -- global user.email 'github-actions@github.com'
          git add *.json
          git commit -m "Auto-update extracted JSON files [skip ci]" || echo "No changes to commit"
          git push
