name: Run model_train.py Now
on:
  workflow_dispatch:

jobs:
  run_matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python_version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run model.py
        run: |
          python model_train.py

      - name: Upload model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-trained-model
          path: 
