name: University Label

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Add university label
        run: python university_label.py
        
      - name: Commit and push results (excluding model)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Model_training/BERTopic_test.csv
          git commit -m "Update topic results from GitHub Actions run" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
